language: c++

before_install:
  - sudo add-apt-repository ppa:eyecreate/haxe -y
  - sudo apt-get update

install:
  # Install haxe
  - sudo apt-get install haxe -y --force-yes
  - mkdir -p ~/haxelib
  - haxelib setup ~/haxelib
  # Compile lime and aether
  - sudo apt-get install mesa-common-dev libgl1-mesa-dev libglu1-mesa-dev -y
  - sudo apt-get install g++-multilib gcc-multilib
  - haxelib install hxcpp
  - haxelib install format
  - git clone https://github.com/openfl/aether.git ~/aether --depth 1
  - haxelib dev aether ~/aether
  - git clone https://github.com/openfl/lime.git ~/lime -b next --recursive --depth 1
  - haxelib dev lime ~/lime
  - haxelib run lime rebuild linux
  - haxelib run lime rebuild tools
  - echo "y" | haxelib run lime setup
  - haxelib dev HaxePunk $TRAVIS_BUILD_DIR

before_script:
  - cd $TRAVIS_BUILD_DIR/tests

script:
  - haxe test.hxml
